apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-inference-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-inference-api
  template:
    metadata:
      labels:
        app: llm-inference-api
    spec:
      containers:
      - name: llm-inference-api
        image: us-central1-docker.pkg.dev/liquid-layout-449900-m0/llm-repo/llm-inference-api:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"